language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - gatsby build

after_script:
  - cd ./public
  - git config user.name "CalElFe"
  - git config user.email "calibur.tonyt@gmail.com"
  - git init
  - git remote add origin "https://CalElFe:${GITHUB_TOKEN}@${GITHUB_REF}"
  - git add .
  - export TRAVIS_TAG=${TRAVIS_TAG:-TRAVIS_BUILD_$(date +'%Y-%m-%d_%H:%M:%S')}
  - git commit -m ${TRAVIS_TAG}
  - git push --force --set-upstream origin master:gh-pages

before_deploy:
  - echo 'Start to deploy'
  - export RELEASE_NAME=${RELEASE_NAME:-release_$(date +'%Y-%m-%d')}
  - zip -r ./out/${RELEASE_NAME}.zip ./public

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./out/${RELEASE_NAME}.zip
  skip_cleanup: true
  on:
    tags: false

branches:
  only:
    - master

env:
  global:
    - GITHUB_REF=github.com/CalElFe/kdvrharts_MC_web.git